services:
  - type: web
    name: colisexpress
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        sync: false
      - key: Stripe__PublishableKey
        sync: false
      - key: Stripe__SecretKey
        sync: false
