// <auto-generated />
using System;
using ColisExpress.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ColisExpress.Infrastructure.Migrations
{
    [DbContext(typeof(ColisExpressDbContext))]
    [Migration("20260504183010_AjoutChampsRefusColis")]
    partial class AjoutChampsRefusColis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ColisExpress.Domain.Entities.Avis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommandeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Note")
                        .HasColumnType("integer");

                    b.Property<Guid>("TransporteurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CommandeId")
                        .IsUnique();

                    b.HasIndex("TransporteurId");

                    b.ToTable("avis", (string)null);
                });

            modelBuilder.Entity("ColisExpress.Domain.Entities.Colis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeColis")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CodeRetrait")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("CommandeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateRefus")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotifRefus")
                        .HasColumnType("text");

                    b.Property<decimal?>("PoidsReel")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("QrCodeData")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("RefusInspecteAdmin")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("RefusInspectePar")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RefusInspectionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefusParRole")
                        .HasColumnType("text");

                    b.Property<Guid?>("RefusParUtilisateurId")
                        .HasColumnType("uuid");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.HasKey("Id");

                    b.HasIndex("CodeColis")
                        .IsUnique();

                    b.HasIndex("CommandeId")
                        .IsUnique();

                    b.HasIndex("Statut");

                    b.ToTable("colis", (string)null);
                });

            modelBuilder.Entity("ColisExpress.Domain.Entities.Commande", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescriptionContenu")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Dimensions")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("FraisService")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("InstructionsParticulieres")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ModeReglement")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("NomDestinataire")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PoidsDeclare")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("PrixTransport")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid?>("RelaisArriveeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelaisDepartId")
                        .HasColumnType("uuid");

                    b.Property<string>("SegmentArrivee")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SegmentDepart")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatutReglement")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("SupplementsTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("TelephoneDestinataire")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("TrajetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TransporteurId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValeurDeclaree")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("VilleDestinataire")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DateCreation");

                    b.HasIndex("RelaisArriveeId");

                    b.HasIndex("RelaisDepartId");

                    b.HasIndex("TrajetId");

                    b.HasIndex("TransporteurId");

                    b.ToTable("commandes", (string)null);
                });

            modelBuilder.Entity("ColisExpress.Domain.Entities.DocumentKyc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CheminFichier")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("ContenuFichier")
                        .HasColumnType("bytea");

                    b.Property<DateTime>("DateSoumission")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateValidation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TransporteurId")
                        .HasColumnType("uuid");

                    b.Property<string>("TypeDocument")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("ValidePar")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TransporteurId");

                    b.ToTable("documents_kyc", (string)null);
                });

            modelBuilder.Entity("ColisExpress.Domain.Entities.EtapeTrajet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("HeureEstimeeArrivee")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("HeureReelleArrivee")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<Guid>("PointRelaisId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RelaisOuvertALArrivee")
                        .HasColumnType("boolean");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TrajetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PointRelaisId");

                    b.HasIndex("TrajetId", "Ordre");

                    b.ToTable("etapes_trajets", (string)null);
                });

            modelBuilder.Entity("ColisExpress.Domain.Entities.EvenementColis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActeurId")
                        .HasColumnType("uuid");

                    b.Property<string>("AncienStatut")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<Guid>("ColisId")
                        .HasColumnType("uuid");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("NouveauStatut")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<string>("PhotoChemin")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ActeurId");

                    b.HasIndex("ColisId");

                    b.HasIndex("DateHeure");

                    b.ToTable("evenements_colis", (string)null);
                });

            modelBuilder.Entity("ColisExpress.Domain.Entities.Paiement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommandeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateEncaissement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateReversement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstReverseAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("Montant")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("ReferenceExterne")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("RelaisEncaisseurId")
                        .HasColumnType("uuid");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("ValidePar")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CommandeId");

                    b.HasIndex("Statut");

                    b.ToTable("paiements", (string)null);
                });

            modelBuilder.Entity("ColisExpress.Domain.Entities.PointRelais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Departement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly?>("HeureFermeture")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("HeureFermetureWeekend")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("HeureOuverture")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("HeureOuvertureWeekend")
                        .HasColumnType("time without time zone");

                    b.Property<string>("JoursOuverture")
                        .HasColumnType("text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<decimal>("MontantCommission")
                        .HasColumnType("numeric");

                    b.Property<string>("NomRelais")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TypeCommission")
                        .HasColumnType("integer");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId")
                        .IsUnique();

                    b.HasIndex("Pays", "Ville");

                    b.ToTable("points_relais", (string)null);
                });

            modelBuilder.Entity("ColisExpress.Domain.Entities.Trajet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CapaciteMaxPoids")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("CapaciteRestante")
                        .HasColumnType("integer");

                    b.Property<string>("Conditions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateDepart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateEstimeeArrivee")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModeTarification")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("NombreMaxColis")
                        .HasColumnType("integer");

                    b.Property<string>("PaysArrivee")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PaysDepart")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PointDepot")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("PrixAuKilo")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("PrixParColis")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal?>("SupplementFragile")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("SupplementUrgent")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("TransporteurId")
                        .HasColumnType("uuid");

                    b.Property<string>("VilleArrivee")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("VilleDepart")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Statut");

                    b.HasIndex("TransporteurId");

                    b.HasIndex("VilleDepart", "VilleArrivee", "DateDepart");

                    b.ToTable("trajets", (string)null);
                });

            modelBuilder.Entity("ColisExpress.Domain.Entities.Transporteur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorridorsActifs")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NombreAvis")
                        .HasColumnType("integer");

                    b.Property<decimal>("NoteMoyenne")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("StatutKyc")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TypeVehicule")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StatutKyc");

                    b.HasIndex("UtilisateurId")
                        .IsUnique();

                    b.ToTable("transporteurs", (string)null);
                });

            modelBuilder.Entity("ColisExpress.Domain.Entities.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Adresse")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DerniereConnexion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailVerifie")
                        .HasColumnType("boolean");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StatutCompte")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.ToTable("utilisateurs", (string)null);
                });

            modelBuilder.Entity("ColisExpress.Domain.Entities.Avis", b =>
                {
                    b.HasOne("ColisExpress.Domain.Entities.Utilisateur", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ColisExpress.Domain.Entities.Commande", "Commande")
                        .WithMany()
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ColisExpress.Domain.Entities.Transporteur", "Transporteur")
                        .WithMany()
                        .HasForeignKey("TransporteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Commande");

                    b.Navigation("Transporteur");
                });

            modelBuilder.Entity("ColisExpress.Domain.Entities.Colis", b =>
                {
                    b.HasOne("ColisExpress.Domain.Entities.Commande", "Commande")
                        .WithOne("Colis")
                        .HasForeignKey("ColisExpress.Domain.Entities.Colis", "CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("ColisExpress.Domain.Entities.Commande", b =>
                {
                    b.HasOne("ColisExpress.Domain.Entities.Utilisateur", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ColisExpress.Domain.Entities.PointRelais", "RelaisArrivee")
                        .WithMany()
                        .HasForeignKey("RelaisArriveeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ColisExpress.Domain.Entities.PointRelais", "RelaisDepart")
                        .WithMany()
                        .HasForeignKey("RelaisDepartId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ColisExpress.Domain.Entities.Trajet", "Trajet")
                        .WithMany()
                        .HasForeignKey("TrajetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ColisExpress.Domain.Entities.Transporteur", "Transporteur")
                        .WithMany()
                        .HasForeignKey("TransporteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("RelaisArrivee");

                    b.Navigation("RelaisDepart");

                    b.Navigation("Trajet");

                    b.Navigation("Transporteur");
                });

            modelBuilder.Entity("ColisExpress.Domain.Entities.DocumentKyc", b =>
                {
                    b.HasOne("ColisExpress.Domain.Entities.Transporteur", "Transporteur")
                        .WithMany("Documents")
                        .HasForeignKey("TransporteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transporteur");
                });

            modelBuilder.Entity("ColisExpress.Domain.Entities.EtapeTrajet", b =>
                {
                    b.HasOne("ColisExpress.Domain.Entities.PointRelais", "PointRelais")
                        .WithMany()
                        .HasForeignKey("PointRelaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ColisExpress.Domain.Entities.Trajet", "Trajet")
                        .WithMany("Etapes")
                        .HasForeignKey("TrajetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PointRelais");

                    b.Navigation("Trajet");
                });

            modelBuilder.Entity("ColisExpress.Domain.Entities.EvenementColis", b =>
                {
                    b.HasOne("ColisExpress.Domain.Entities.Utilisateur", "Acteur")
                        .WithMany()
                        .HasForeignKey("ActeurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ColisExpress.Domain.Entities.Colis", "Colis")
                        .WithMany("Evenements")
                        .HasForeignKey("ColisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acteur");

                    b.Navigation("Colis");
                });

            modelBuilder.Entity("ColisExpress.Domain.Entities.Paiement", b =>
                {
                    b.HasOne("ColisExpress.Domain.Entities.Commande", "Commande")
                        .WithMany()
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("ColisExpress.Domain.Entities.PointRelais", b =>
                {
                    b.HasOne("ColisExpress.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithOne()
                        .HasForeignKey("ColisExpress.Domain.Entities.PointRelais", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ColisExpress.Domain.Entities.Trajet", b =>
                {
                    b.HasOne("ColisExpress.Domain.Entities.Transporteur", "Transporteur")
                        .WithMany()
                        .HasForeignKey("TransporteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Transporteur");
                });

            modelBuilder.Entity("ColisExpress.Domain.Entities.Transporteur", b =>
                {
                    b.HasOne("ColisExpress.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithOne()
                        .HasForeignKey("ColisExpress.Domain.Entities.Transporteur", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ColisExpress.Domain.Entities.Colis", b =>
                {
                    b.Navigation("Evenements");
                });

            modelBuilder.Entity("ColisExpress.Domain.Entities.Commande", b =>
                {
                    b.Navigation("Colis");
                });

            modelBuilder.Entity("ColisExpress.Domain.Entities.Trajet", b =>
                {
                    b.Navigation("Etapes");
                });

            modelBuilder.Entity("ColisExpress.Domain.Entities.Transporteur", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
